---
    - name: install MongoDB
      hosts: all
      become: true
      tasks:
    
      - name: add key
        apt_key:
          id: 0xd68fa50fea312927
          keyserver: keyserver.ubuntu.com
    
      - name: add repository
        apt_repository:
          repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
          state: present
    
      - name: install db package
        apt:
          name: mongodb-org
          state: present
    
      - name: db configure
        systemd:
          name: mongod
          enabled: yes
          